title: Klabo.blog 
email: joel@klabo.blog 
description: >- # this means to ignore newlines until "baseurl:"
  Writing about Bitcoin and the Lightning Network
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://klabo.blog" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: joelklabo 
github_username: joelklabo 

# Build settings
theme: minima
plugins:
  - jekyll-feed
